name: Build and Deploy Yaht Client to Dist

on:
  workflow_dispatch:

env:
  NODE_VERSION: '12.x'
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-client:
    name: Build Yaht Client App
    runs-on: macOS-latest

    steps:        
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build and deploy
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          DEBUG: electron-builder

    
